name: document_validator_client
description: A client for the gRPC document validator service.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# App dependencies go here
dependencies:
  grpc: ^4.2.0
  # e.g., http: ^1.1.0

# Dependencies for development/testing go here
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0