// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: proto/validator/validator.proto

package validator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocumentNumber string                 `protobuf:"bytes,1,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_proto_validator_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validator_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_validator_validator_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationRequest) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

type ValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_proto_validator_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_validator_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_validator_validator_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_proto_validator_validator_proto protoreflect.FileDescriptor

const file_proto_validator_validator_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/validator/validator.proto\x12\tvalidator\"<\n" +
	"\x11ValidationRequest\x12'\n" +
	"\x0fdocument_number\x18\x01 \x01(\tR\x0edocumentNumber\"/\n" +
	"\x12ValidationResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid2^\n" +
	"\tValidator\x12Q\n" +
	"\x10ValidateDocument\x12\x1c.validator.ValidationRequest\x1a\x1d.validator.ValidationResponse\"\x00B+Z)document-validator-server/proto/validatorb\x06proto3"

var (
	file_proto_validator_validator_proto_rawDescOnce sync.Once
	file_proto_validator_validator_proto_rawDescData []byte
)

func file_proto_validator_validator_proto_rawDescGZIP() []byte {
	file_proto_validator_validator_proto_rawDescOnce.Do(func() {
		file_proto_validator_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_validator_validator_proto_rawDesc), len(file_proto_validator_validator_proto_rawDesc)))
	})
	return file_proto_validator_validator_proto_rawDescData
}

var file_proto_validator_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_validator_validator_proto_goTypes = []any{
	(*ValidationRequest)(nil),  // 0: validator.ValidationRequest
	(*ValidationResponse)(nil), // 1: validator.ValidationResponse
}
var file_proto_validator_validator_proto_depIdxs = []int32{
	0, // 0: validator.Validator.ValidateDocument:input_type -> validator.ValidationRequest
	1, // 1: validator.Validator.ValidateDocument:output_type -> validator.ValidationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_validator_validator_proto_init() }
func file_proto_validator_validator_proto_init() {
	if File_proto_validator_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_validator_validator_proto_rawDesc), len(file_proto_validator_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_validator_validator_proto_goTypes,
		DependencyIndexes: file_proto_validator_validator_proto_depIdxs,
		MessageInfos:      file_proto_validator_validator_proto_msgTypes,
	}.Build()
	File_proto_validator_validator_proto = out.File
	file_proto_validator_validator_proto_goTypes = nil
	file_proto_validator_validator_proto_depIdxs = nil
}
